config/routes.rb
Rails.application.routes.draw do
  get 'movies/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end

  # Defines the root path route ("/")
  root "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }

  belongs_to :movie
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list_id = params[:list_id]
    @bookmark.movie_id = params[:bookmark][:movie_id]
    if @bookmark.save!
      redirect_to list_path(params[:list_id])
    end
  end

  def destroy
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save!
      redirect_to @list
    else
      render :new
    end
  end

  def destroy
    @list.destroy
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def find_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>Create a bookmark</h1>

<%= simple_form_for @bookmark do |f| %>
  <%= f.input :comment %>
  <%= f.input :movie, collection: @movies_list%>
  <%= f.button :submit%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<h1>List de lists</h1>

<%= link_to 'New List', new_list_path%>

<% @lists.each do |list| %>
  <p><%= list.name %></p>
  <%= link_to 'Show', list_path(list) %>
<%end%>

app/views/lists/new.html.erb
<h1>Create a new list</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo%>
  <%= f.button :submit%>

<% end %>

app/views/lists/show.html.erb
<h1 class="text-center">Here your list</h1>

<p><%= @list.name %></p>

<% if @list.photo.attached?%>
  <%= cl_image_tag @list.photo.key%>
<% end %>


<%@list.bookmarks.each do |bookmark| %>
<div class="card d-flex" style="max-width: 400px!important; max-height: 400px!important;">
  <div style="height: 200px;">
    <img src="<%=bookmark.movie.poster_url%>" class="card-img-top" alt="">
  </div>
  <div class="card-body" style="height: 200px;">
    <h5 class="card-title"><%= bookmark.movie.title %></h5>
    <p class="card-text"><%= bookmark.movie.overview %></p>
    <p class="card-text"><%= bookmark.comment %></p>
  </div>
</div>
<% end %>

<p>Create e bookmark</p>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie, collection: Movie.all%>
  <%= f.input :comment%>
  <%= f.button :submit%>
<% end %>

<%= link_to "Back", lists_path %>

app/views/movies/index.html.erb
<h1>Movies#index</h1>
<p>Find me in app/views/movies/index.html.erb</p>